services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=devconnector
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    restart: always
    ports:
      - 27017:27017

  mongo-seed:
    build:
      context: ./.data
      dockerfile: Dockerfile
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 80:80

