services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
#    ports:
#      - 5000:5000
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    restart: always
    ports:
      - 27017:27017

  mongo-seed:
    build:
      context: ./.data
      dockerfile: Dockerfile
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
#    ports:
#      - 80:80
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 80:80

