services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=devconnector
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    restart: always
    ports:
      - 27017:27017

  mongo-seed:
    build:
      context: ./.data
      dockerfile: Dockerfile
    depends_on:
      - mongo